# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20160804_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='trip',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.Trip'),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='photo',
            field=models.ImageField(height_field='image_height', upload_to='photos/%Y/', width_field='image_width'),
        ),
    ]
